version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data  # Carpeta local para persistencia de datos
    command: ["postgres", "-c", "listen_addresses=*"]  # Permitir conexiones externas

  app:
    build: .
    container_name: nestjs_app
    restart: always
    depends_on:
      - db
    ports:
      - "3000:3000"  # Exponer el puerto de la app en el puerto 3000
    env_file:
      - .env  # Cargar las variables de entorno desde el archivo .env

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"  # Exponer el puerto de Redis
